### PR TITLE
Check for legacy React classes in layout renderer. Fixes #26

### LINKED ISSUE #26: ReactLayoutRenderer doesn't work with React.createClass layouts
(Such as used in galaxy-server.)

The check added in https://github.com/meteor/chromatic/commit/8b85b53953bcf3b89cf600d36131ec273af2c35c thinks it's a function to call.

### PR DESCRIPTION
**Pull request by timbotnik**

### CODE REVIEW

**Comment by timbotnik** [comment]
@glasser @daniman merging this as tested with galaxy + optics

**Comment by glasser** [comment]
I don't feel like I can usefully review this but it seems like a thing that could accomplish a goal and I trust you.

**Comment by timbotnik** [comment]
Haha.  I know what you mean.  My approach with this package is that it will hopefully go away in the not too distant future and we'll switch to `react-router` so just making it work is enough.

**Comment by glasser** [comment]
I... opened that issue? I have no idea what the words in it are.

**Pull request merged**
