### PR TITLE
Meteor 1.3 support

### PR DESCRIPTION
**Pull request by zhenyasav**
WIP
- [x] icons / icon fonts from borealis
- [x] optimize import structure (`import Chromatic from 'chromatic'` should be all you need)
- [ ] publish packages
- [ ] component packages
- [ ] test meteor add in clean project
- [ ] test that chromatic explorer isnt built in release mode
- [ ] lint cleanup

### CODE REVIEW

**Comment by ctzurcanu** [comment]
No activity since April. Is this project dead?

**Comment by loredanacirstea** [comment]
I built upon the `npm` branch and added partial support for Meteor 1.3 and React 15 + some nice features:

- Dynamic exploration, design and testing - dat.GUI interface for changing React props
- Just copy-paste the new JSON settings into your React component
- Supports HTML and SVG
- In work: having your stylesheet classes at your GUI fingertips

Check:
https://github.com/oro8oro/chromatic
Short demo: https://www.youtube.com/edit?video_id=DVFj2A6789Y

If you guys want to continue Chromatic and would like some help, I can prepare a pull request.

By the way, thank you, Chromatic is great!

**Comment by zhenyasav** [comment]
Thank you @loredanacirstea a PR would be fantastic :)

**Comment by ffxsam** [comment]
@loredanacirstea Holy crap, great work!

**Comment by loredanacirstea** [comment]
https://github.com/meteor/chromatic/pull/12 - support for meteor 1.3

The dat.GUI interface for dynamic testing will come in another PR. By the way, thanx to @ctzurcanu - adding this was his idea.

**Pull request merged**
